blog/urls.py
from django.urls import path
from blog.views import BlogListView

app_name = 'blog'

urlpatterns = [
    path('', BlogListView.as_view(), name='list'),
]

classes/urls.py
from django.urls import path
from classes.views import ClassesListView

app_name = 'classes'

urlpatterns = [
    path('', ClassesListView.as_view(), name='list')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('classes/', include('classes.urls', namespace='classes')),
    path('events/', include('events.urls', namespace='events')),
    path('shop/', include('shop.urls', namespace='shop')),
]

events/urls.py
from django.urls import path
from events.views import EventsListView

app_name = 'events'

urlpatterns = [
    path('', EventsListView.as_view(), name='list')
]

pages/urls.py
from django.urls import path
from pages.views import HomePageView, ContactListView

app_name = 'pages'

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('contact/', ContactListView.as_view(), name='contact'),
]

shop/urls.py
from django.urls import path
from shop.views import ShopListView

app_name = 'shop'

urlpatterns = [
    path('', ShopListView.as_view(), name='list'),
]

blog/models.py
from django.db import models

# Create your models here.

classes/models.py
from django.db import models

# Create your models here.

events/models.py
from django.db import models

# Create your models here.

pages/models.py
from django.db import models

# Create your models here.

shop/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.views.generic import TemplateView


class BlogListView(TemplateView):
    template_name = 'blog/blog.html'

classes/views.py
from django.views.generic import TemplateView


class ClassesListView(TemplateView):
    template_name = 'classes/classes-list.html'

events/views.py
from django.views.generic import TemplateView


class EventsListView(TemplateView):
    template_name = 'events/events-list.html'

pages/views.py
from django.views.generic import TemplateView


class HomePageView(TemplateView):
    template_name = 'home.html'


class ContactListView(TemplateView):
    template_name = 'contactus.html'

shop/views.py
from django.views.generic import TemplateView


class ShopListView(TemplateView):
    template_name = 'shop/checkout.html'

templates/classes/classes-list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<!--classes-3-columns23:37  -->
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<title>EducationPress - The Most Complete Education Solution</title>


<!--[if lt IE 9]>
  <script src="{% static 'js/html5shiv.min.js' %}"></script>
  <script src="{% static 'js/respond.min.js' %}"></script>
<![endif]-->

<link rel="shortcut icon" href="{% static 'images/favicon.png' %}" />

<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">

<link rel="stylesheet" href="{% static 'css/linearicons-free.css' %}">

<link rel="stylesheet" href="{% static 'css/simple-line-icons.css' %}">

<link rel="stylesheet" href="{% static 'vendor/fancybox/css/fancybox.css' %}">

<link rel="stylesheet" href="{% static 'css/global.css' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="{% static 'css/kindergarten.css' %}">
</head>
<body>

<div class="header_meta header_meta_one">
    <div class="container">
        <div class="row">
            <ul class="social">
                <li><a href="home.html#"><i class="fa fa-twitter"></i></a></li>
                <li><a href="home.html#"><i class="fa fa-facebook-square"></i></a></li>
                <li><a href="home.html#"><i class="fa fa-linkedin-square"></i></a></li>
                <li><a href="home.html#"><i class="fa fa-pinterest"></i></a></li>
                <li><a href="home.html#"><i class="fa fa-instagram"></i></a></li>
                <li><a href="home.html#"><i class="fa fa-youtube"></i></a></li>
            </ul>
            <nav class="meta-login">
                <ul>
                    <li class="clock"><i class="lnr lnr-clock"></i>Mon - Fri : 8:00 - 12:00</li>
                    <li class="call"><i class="lnr lnr-smartphone"></i>Call Us +731 234 5678</li>
                    <li><a href="home.html#login-form" class="fancybox">Login</a></li>
                    <li><a href="home.html#register-form" class="fancybox">Signup</a></li>
                </ul>
            </nav>
        </div>
    </div>
</div>

<header class="site-header home-one" id="masthead">
    <div class="container">
        <div class="row">
            <div class="site-branding col-xs-12 col-sm-3">
                <a href="home.html#"><img alt="educationpress" class="brand" src="{% static 'images/logo5.png' %}" /></a>
            </div>
            <nav class="main-navigation navbar navbar-default" id="site-navigation">
                <div class="navbar-header">
                    <button data-target=".navbar-ex1-collapse" data-toggle="collapse" class="navbar-toggle" type="button">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse navbar-ex1-collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'pages:home' %}">Home</a></li>
                        <li><a href="{% url 'classes:list' %}">Classes</a></li>
                        <li><a href="{% url 'events:list' %}">Events</a></li>
                        <li><a href="{% url 'blog:list' %}">Blog</a></li>
                        <li><a href="{% url 'shop:list' %}">Shop</a></li>
                        <li><a href="{% url 'pages:contact' %}">Contact Us</a></li>
                    </ul>
                </div>
            </nav>
        </div>
    </div>
</header>


</header>
<div class="breadcrumb-section">
<div class="container">
<div class="row">
<header class="entry-header">
<h1 class="entry-title">Classes</h1>
</header>
</div> 
</div>
</div>
<div class="page-spacer clearfix">
<div id="primary">
<div class="container">
<div class="row">
<main id="main" class="site-main col-xs-12 ">
<div class="school-classes inner-classes">
<div class="col-xs-12 col-sm-4 zoom">
<div class="classes">
<a href="classes-list.html#" class="img-thumb"><figure>
 <img src="{% static 'images/use_img/course_img1.png' %}" alt="" /></figure></a>
<div class="classes-info">
<div class="price">$55 <small></small></div>
<h3><a href="classes-list.html#">Features Name Here Lorem ipsum dolor </a></h3>
<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
<ul class="classes-time">
<li><span>2 - 5</span>
Year old </li>
<li><span>24</span>
Class Size</li>
<li><span>9:00 - 10:00</span>
Class Duration</li>
</ul>
</div>
</div>
</div> 
<div class="col-xs-12 col-sm-4 zoom">
<div class="classes">
<a href="classes-list.html#" class="img-thumb"><figure>
<img src="{% static 'images/use_img/course_img2.png' %}" alt="" /></figure></a>
<div class="classes-info">
<div class="price">$55 <small></small></div>
<h3><a href="classes-list.html#">Features Name Here</a></h3>
<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
<ul class="classes-time">
<li><span>2 - 5</span>
Year old </li>
<li><span>24</span>
Class Size</li>
<li><span>9:00 - 10:00</span>
Class Duration</li>
</ul>
</div>
</div>
</div> 
<div class="col-xs-12 col-sm-4 zoom">
<div class="classes">
<a class="img-thumb video_player" href="classes-list.html#">
<figure>
<embed width="100%" height="265" src="https://www.youtube.com/embed/zSaSxgL9SWI"></embed>
</figure>
</a>
<div class="classes-info">
<div class="price">$55 <small></small></div>
<h3><a href="classes-list.html#">Features Name Here</a></h3>
<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
<ul class="classes-time">
<li><span>2 - 5</span>
Year old </li>
<li><span>24</span>
Class Size</li>
<li><span>9:00 - 10:00</span>
Class Duration</li>
</ul>
</div>
</div>
</div> 
<div class="col-xs-12 col-sm-4 zoom">
<div class="classes">
<a href="classes-list.html#" class="img-thumb"><figure>
<img src="{% static 'images/use_img/course_img4.png' %}" alt="" /></figure></a>
<div class="classes-info">
<div class="price">$55 <small></small></div>
<h3><a href="classes-list.html#">Features Name Here</a></h3>
<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
 <ul class="classes-time">
<li><span>2 - 5</span>
Year old </li>
<li><span>24</span>
Class Size</li>
<li><span>9:00 - 10:00</span>
Class Duration</li>
</ul>
</div>
</div>
</div> 
<div class="col-xs-12 col-sm-4 zoom">
<div class="classes">
<a href="classes-list.html#" class="img-thumb"><figure>
<img src="{% static 'images/use_img/course_img5.png' %}" alt="" /></figure></a>
<div class="classes-info">
<div class="price">$55 <small></small></div>
<h3><a href="classes-list.html#">Features Name Here</a></h3>
<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
<ul class="classes-time">
<li><span>2 - 5</span>
Year old </li>
<li><span>24</span>
Class Size</li>
<li><span>9:00 - 10:00</span>
Class Duration</li>
</ul>
</div>
</div>
</div> 
<div class="col-xs-12 col-sm-4 zoom">
<div class="classes">
<a href="classes-list.html#" class="img-thumb"><figure>
<img src="{% static 'images/use_img/course_img6.png' %}" alt="" /></figure></a>
<div class="classes-info">
<div class="price">$55 <small></small></div>
<h3><a href="classes-list.html#">Features Name Here</a></h3>
<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
<ul class="classes-time">
<li><span>2 - 5</span>
Year old </li>
<li><span>24</span>
Class Size</li>
<li><span>9:00 - 10:00</span>
Class Duration</li>
</ul>
</div>
</div>
</div> 
</div> 
<div class="pagination">
<span class="page-numbers current">1</span>
<a href="classes-list.html#" class="page-numbers">2</a>
<a href="classes-list.html#" class="page-numbers">3</a>
<a href="classes-list.html#" class="next page-numbers"><i class="fa fa-angle-right"></i></a>
</div>
</main>
</div> 
</div> 
</div>
</div> 
<section class="call-to-action">
<div class="container">
<div class="row">
<div class="col-xs-12">
<div class="col-xs-12 col-sm-8">
<h3>Remaining essentially unchanged.</h3>
<p>When an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
</div>
<a href="classes-list.html#" class="btn btn-medium btn-default pull-right">Know More <i class="lnr lnr-arrow-right"></i></a>
</div>
</div> 
</div>
</section> 
<footer class="site-footer" id="colophon">
<div class="container">
<div class="row">
<div class="col-xs-12 col-sm-4"><img src="{% static 'images/logo5.png' %}" alt="" /></div>
</div>
<div class="row">
<div class="col-xs-12 col-sm-4 footer-widget">
<aside class="widget widget_text">
<div class="textwidget">
The point of using Lorem Ipsum is that it has a more or less normal distribution of letters, as opposed to using
'Content here, content here', making it look like readable English.
</div>
</aside>
<aside class="widget socialmedia-widget">
<ul class="social">
<li><a href="classes-list.html#"><i class="fa fa-twitter"></i></a></li>
<li><a href="classes-list.html#"><i class="fa fa-facebook-square"></i></a></li>
<li><a href="classes-list.html#"><i class="fa fa-linkedin-square"></i></a></li>
<li><a href="classes-list.html#"><i class="fa fa-pinterest"></i></a></li>
<li><a href="classes-list.html#"><i class="fa fa-instagram"></i></a></li>
<li><a href="classes-list.html#"><i class="fa fa-youtube"></i></a></li>
</ul>
</aside>
</div>
<div class="col-xs-12 col-sm-4 footer-widget">
<aside class="widget widget_nav_menu">
<ul class="menu">
<li><a href="classes-list.html#">Home</a></li>
<li><a href="classes-list.html#">Shortcodes</a></li>
<li><a href="classes-list.html#">about US</a></li>
<li><a href="classes-list.html#">Blog</a></li>
<li><a href="classes-list.html#">classes</a></li>
<li><a href="classes-list.html#">Contact US</a></li>
<li><a href="classes-list.html#">Teachers</a></li>
<li><a href="classes-list.html#">Privacy Policy</a></li>
<li><a href="classes-list.html#">Events</a></li>
</ul>
</aside>
</div>
<div class="col-xs-12 col-sm-4 footer-widget">
<aside class="widget newsletter-widget">
<h3>Sign up now</h3>
<p>When an printer took a galley of type and scrambled it to make a type specimen book.</p>
<form id="newsletter">
<input type="email" name="email" class="form-control" placeholder="Email" />
<button type="submit" value="" class="btn btn-orange btn-medium"><i class="lnr lnr-arrow-right"></i></button>
</form>
</aside>
</div>
</div> 
</div>

<div class="footer-bottom">
<div class="container">
<div class="row">
<div class="copyright">

<p class="develop col-xs-12 col-sm-4 text-right"><a target="_blank" href="https://www.templateshub.net">Templates Hub</a> </p>
</div>
</div>
</div>
</div>
</footer>


<div id="login-form" style="display:none;">
<div class="row">
<h3>Login</h3>
<p>Please Login to Create a New Course</p>
<form id="login" action="classes-list.html#">
<input name="email" type="text" placeholder="Email or Username">
<input name="password" type="text" placeholder="Password">
<div class="row remeber">
<label><input name="rember" type="checkbox" value=""> Remember Me</label>
<a href="classes-list.html#">Forgot Password?</a>
</div>
<div class="text-center button">
<input name="Login" type="button" value="Login Now">
</div>
</form>
</div> 
</div> 

<div id="register-form" style="display:none;">
<div class="row">
<h3>Register</h3>
<p>Please Register to Create a New Account</p>
<form id="register" action="classes-list.html#">
<input name="name" type="text" placeholder="Name">
<input name="username" type="text" placeholder="Username">
<input name="email" type="text" placeholder="Email">
<input name="password" type="text" placeholder="Password">
<input name="confirmpassword" type="text" placeholder="Confirm Password">
<div class="row new-login">
Already have an account? <a href="classes-list.html#">Login to your account! </a>
</div>
<div class="text-center button">
<input name="create-account" type="button" value="Create an Account">
</div>
</form>
</div>
</div>


<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

<script src="{% static 'js/theme.js' %}"></script>

<script type="text/javascript" src="{% static 'vendor/fancybox/js/jquery.fancybox.js' %}"></script>
<script type="text/javascript" src="{% static 'vendor/fancybox/js/custom.fancybox.js' %}"></script>
<script>
jQuery.noConflict();
jQuery('.fancybox').fancybox();
</script>
<script type="text/javascript">
jQuery.noConflict();
	jQuery( document ).ready(function( $ ) {
		$('#list').click(function(event){event.preventDefault();$('#products .courses').addClass('list-group-item');});
		$('#grid').click(function(event){event.preventDefault();$('#products .courses').removeClass('list-group-item');
		
		$('#products .courses').addClass('grid-group-item');});
	});
</script>
</body>

<!--classes-3-columns23:37  -->
</html>

templates/contactus.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<!--contactus23:56  -->
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<title>EducationPress - The Most Complete Education Solution</title>


<!--[if lt IE 9]>
  <script src="{% static 'js/html5shiv.min.js' %}"></script>
  <script src="{% static 'js/respond.min.js' %}"></script>
<![endif]-->

<link rel="shortcut icon" href="{% static 'images/favicon.png' %}" />

<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">

<link rel="stylesheet" href="{% static 'css/linearicons-free.css' %}">

<link rel="stylesheet" href="{% static 'css/simple-line-icons.css' %}">

<link rel="stylesheet" href="{% static 'vendor/fancybox/css/fancybox.css' %}">

<link rel="stylesheet" href="{% static 'css/global.css' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="{% static 'css/kindergarten.css' %}">
</head>
<body>

<div class="header_meta header_meta_one">
    <div class="container">
        <div class="row">
            <ul class="social">
                <li><a href="home.html#"><i class="fa fa-twitter"></i></a></li>
                <li><a href="home.html#"><i class="fa fa-facebook-square"></i></a></li>
                <li><a href="home.html#"><i class="fa fa-linkedin-square"></i></a></li>
                <li><a href="home.html#"><i class="fa fa-pinterest"></i></a></li>
                <li><a href="home.html#"><i class="fa fa-instagram"></i></a></li>
                <li><a href="home.html#"><i class="fa fa-youtube"></i></a></li>
            </ul>
            <nav class="meta-login">
                <ul>
                    <li class="clock"><i class="lnr lnr-clock"></i>Mon - Fri : 8:00 - 12:00</li>
                    <li class="call"><i class="lnr lnr-smartphone"></i>Call Us +731 234 5678</li>
                    <li><a href="home.html#login-form" class="fancybox">Login</a></li>
                    <li><a href="home.html#register-form" class="fancybox">Signup</a></li>
                </ul>
            </nav>
        </div>
    </div>
</div>

<header class="site-header home-one" id="masthead">
    <div class="container">
        <div class="row">
            <div class="site-branding col-xs-12 col-sm-3">
                <a href="home.html#"><img alt="educationpress" class="brand" src="{% static 'images/logo5.png' %}" /></a>
            </div>
            <nav class="main-navigation navbar navbar-default" id="site-navigation">
                <div class="navbar-header">
                    <button data-target=".navbar-ex1-collapse" data-toggle="collapse" class="navbar-toggle" type="button">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse navbar-ex1-collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'pages:home' %}">Home</a></li>
                        <li><a href="{% url 'classes:list' %}">Classes</a></li>
                        <li><a href="{% url 'events:list' %}">Events</a></li>
                        <li><a href="{% url 'blog:list' %}">Blog</a></li>
                        <li><a href="{% url 'shop:list' %}">Shop</a></li>
                        <li><a href="{% url 'pages:contact' %}">Contact Us</a></li>
                    </ul>
                </div>
            </nav>
        </div>
    </div>
</header>


</header>
<div class="breadcrumb-section">
<div class="container">
<div class="row">
<header class="entry-header">
<h1 class="entry-title">Contact Us</h1>
</header>
</div> 
</div>
</div>
<div class="page-spacer clearfix">
<div class="container">
<div class="row">
<div class="col-xs-12 col-sm-6 contact-form">
<h3>Stay in Touch</h3>
<p>Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>
<div id="success" class="alert alert-success">Your message succesfully sent!</div>
<div id="error" class="alert alert-danger">Opps! There is something wrong. Please try again</div>
<form class="contactform" method="post" action="http://demos.themecycle.com/eduhtml/edu-kindergarten/contact_process.php" id="contactForm">
<p><input type="text" placeholder="First Name" required id="fname" name="fname"></p>
<p><input type="text" placeholder="Last Name" required id="lname" name="lname"></p>
<p><input type="text" id="phone" name="phone" placeholder="Phone Number"></p>
<p><input type="email" id="email" name="email" required placeholder="Email Address"></p>
<p><textarea placeholder="Message" name="message" id="message" rows="10" cols="40"></textarea></p>
<p><input type="submit" class="btn btn-default" value="submit now">
</form>
</div> 


<div class="col-xs-12 col-sm-6 contact-info">
<div class="col-xs-12 col-sm-6">
<h3 class="head-border-default">Education Press</h3>
<p class="address"><i class="fa fa-map-marker"></i>2036 Thunder Road CA 94612
Oakland, opp. of geon tower
Pincode - 580089</p>
<p class="email"><i class="lnr lnr-envelope"></i><a href="https://websitedownloader.io/cdn-cgi/l/email-protection" class="__cf_email__" data-cfemail="f39a9d959cb39697869092879a9c9d8381968080dd909c9e">[email&#160;protected]</a></p>
<ul class="social-icons">
<li><a href="contactus.html#"><i class="fa fa-facebook"></i></a></li>
<li><a href="contactus.html#"><i class="fa fa-google-plus"></i></a></li>
<li><a href="contactus.html#"><i class="fa fa-twitter"></i></a></li>
<li><a href="contactus.html#"><i class="fa fa-linkedin"></i></a></li>
</ul>
</div>
<div class="col-xs-12 col-sm-6">
<h3 class="head-border-default">Customer Supprt</h3>
<p class="phone"><i class="fa fa-phone"></i>731-234-5678</p>
<p class="email"><i class="lnr lnr-envelope"></i><a href="https://websitedownloader.io/cdn-cgi/l/email-protection" class="__cf_email__" data-cfemail="c2b1b7b2b2adb0b682a7a6b7a1b6abadacb2b0a7b1b1">[email&#160;protected]</a>,com</p>
</div>
<div class="col-xs-12 col-sm-12 have-question">
<h3>Have Any Question?</h3>
<p>Various versions years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>
<a href="contactus.html#" class="btn btn-blue btn-medium">Ask a Question</a>
</div>
</div> 
<div class="col-xs-12 col-sm-12 map-location">
<h3 class="head-border-default">Map and Location</h3>

<div id="mapBox" class="row m0" data-lat="37.3818288" data-lon="-122.0636325" data-zoom="15" data-marker="{% static 'images/map-marker.html' %}"></div>
</div>
</div> 
</div>
</div> 
<section class="call-to-action">
<div class="container">
<div class="row">
<div class="col-xs-12">
<div class="col-xs-12 col-sm-8">
<h3>Remaining essentially unchanged.</h3>
<p>When an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
</div>
<a href="contactus.html#" class="btn btn-medium btn-default pull-right">Know More <i class="lnr lnr-arrow-right"></i></a>
</div>
</div> 
</div>
</section> 
<footer class="site-footer" id="colophon">
<div class="container">
<div class="row">
<div class="col-xs-12 col-sm-4"><img src="{% static 'images/logo5.png' %}" alt="" /></div>
</div>
<div class="row">
<div class="col-xs-12 col-sm-4 footer-widget">
<aside class="widget widget_text">
<div class="textwidget">
The point of using Lorem Ipsum is that it has a more or less normal distribution of letters, as opposed to using
'Content here, content here', making it look like readable English.
</div>
</aside>
<aside class="widget socialmedia-widget">
<ul class="social">
<li><a href="contactus.html#"><i class="fa fa-twitter"></i></a></li>
<li><a href="contactus.html#"><i class="fa fa-facebook-square"></i></a></li>
<li><a href="contactus.html#"><i class="fa fa-linkedin-square"></i></a></li>
<li><a href="contactus.html#"><i class="fa fa-pinterest"></i></a></li>
<li><a href="contactus.html#"><i class="fa fa-instagram"></i></a></li>
<li><a href="contactus.html#"><i class="fa fa-youtube"></i></a></li>
</ul>
</aside>
</div>
<div class="col-xs-12 col-sm-4 footer-widget">
<aside class="widget widget_nav_menu">
<ul class="menu">
<li><a href="contactus.html#">Home</a></li>
<li><a href="contactus.html#">Shortcodes</a></li>
<li><a href="contactus.html#">about US</a></li>
<li><a href="contactus.html#">Blog</a></li>
<li><a href="contactus.html#">classes</a></li>
<li><a href="contactus.html#">Contact US</a></li>
<li><a href="contactus.html#">Teachers</a></li>
<li><a href="contactus.html#">Privacy Policy</a></li>
<li><a href="contactus.html#">Events</a></li>
</ul>
</aside>
</div>
<div class="col-xs-12 col-sm-4 footer-widget">
<aside class="widget newsletter-widget">
<h3>Sign up now</h3>
<p>When an printer took a galley of type and scrambled it to make a type specimen book.</p>
<form id="newsletter">
<input type="email" name="email" class="form-control" placeholder="Email" />
<button type="submit" value="" class="btn btn-orange btn-medium"><i class="lnr lnr-arrow-right"></i></button>
</form>
</aside>
</div>
</div> 
</div>

<div class="footer-bottom">
<div class="container">
<div class="row">
<div class="copyright">

<p class="develop col-xs-12 col-sm-4 text-right"><a target="_blank" href="https://www.templateshub.net">Templates Hub</a> </p>
</div>
</div>
</div>
</div>
</footer>


<div id="login-form" style="display:none;">
<div class="row">
<h3>Login</h3>
<p>Please Login to Create a New Course</p>
<form id="login" action="contactus.html#">
<input name="email" type="text" placeholder="Email or Username">
<input name="password" type="text" placeholder="Password">
<div class="row remeber">
<label><input name="rember" type="checkbox" value=""> Remember Me</label>
<a href="contactus.html#">Forgot Password?</a>
</div>
<div class="text-center button">
<input name="Login" type="button" value="Login Now">
</div>
</form>
</div> 
</div> 

<div id="register-form" style="display:none;">
<div class="row">
<h3>Register</h3>
<p>Please Register to Create a New Account</p>
<form id="register" action="contactus.html#">
<input name="name" type="text" placeholder="Name">
<input name="username" type="text" placeholder="Username">
<input name="email" type="text" placeholder="Email">
<input name="password" type="text" placeholder="Password">
<input name="confirmpassword" type="text" placeholder="Confirm Password">
<div class="row new-login">
Already have an account? <a href="contactus.html#">Login to your account! </a>
</div>
<div class="text-center button">
<input name="create-account" type="button" value="Create an Account">
</div>
</form>
</div>
</div>



<script src="{% static 'js/jquery.validate.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

<script src="{% static 'js/jquery.form.js' %}"></script>
<script src="{% static 'js/contact.js' %}"></script>

<script src="{% static 'js/theme.js' %}"></script>

<script type="text/javascript" src="{% static 'vendor/fancybox/js/jquery.fancybox.js' %}"></script>
<script type="text/javascript" src="{% static 'vendor/fancybox/js/custom.fancybox.js' %}"></script>
<script>
jQuery.noConflict();
jQuery('.fancybox').fancybox();
</script>

<script src="https://maps.googleapis.com/maps/api/js?callback=mapBox"></script>
</body>

<!--contactus23:56  -->
</html>